trigger:
- none

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/HelloWorld.sln'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  displayName: 'Run Nuget Restore'
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: Publish Solution
  inputs:
    command: 'publish'
    publishWebProjects: true
    projects: $(solution)
    arguments: '--configuration Release /p:DebugType=None /p:DebugSymbols=false --output $(Build.SourcesDirectory)\build\zip\Project_Sample -v d'
    modifyOutputPath: false
    zipAfterPublish: true
    workingDirectory: '$(Build.SourcesDirectory)'

- task: PublishBuildArtifacts@1
  displayName: Publish zip file
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)\build\zip\Project_Sample'
    ArtifactName: 'drop'
    publishLocation: 'Container'