trigger:
- master

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetCommand@2
  displayName: 'Run Nuget Restore'
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  enabled: true
  displayName: Publish - $(solution)
  inputs:
    command: 'publish'
    publishWebProjects: true
    projects: $(solution)
    arguments: '--configuration Release /p:DebugType=None /p:DebugSymbols=false --output $(Build.SourcesDirectory)\build\zip\Project_Sample -v d'
    modifyOutputPath: false
    zipAfterPublish: true
    workingDirectory: '$(Build.SourcesDirectory)'

- task: PublishBuildArtifacts@1
  displayName: Publish zip file
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)\build\zip\Project_Sample'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  condition: or(contains(variables['build.sourceBranch'], 'refs/heads/master'), contains(variables['build.sourceBranch'], 'refs/heads/Development'))  

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
