trigger:
  - none
pr:
  - none

resources:
  repositories:
    - repository: CMTeam
      type : github
      endpoint: MyGithubServiceConnection
      name: RamkrishnaKakani/CMTeam
      ref : master

  pipelines:
  - pipeline: Project_Sample_Build
    source: Project_Sample_Build
    trigger: true    

steps:
- checkout: self
- checkout: CMTeam

- download: Project_Sample_Build
  artifact: 'drop'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Zip File'
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/vProject_Sample_Build/drop'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- template: Template/terraform_deploy.yml
  parameters:
    environment: "$(env)"
    working_dir: "$(Build.SourcesDirectory)/CMTeam/infra"
    serviceconn_name : "Terraform_ServiceConnection"
    project_name : "$(project)" 
 