trigger: none
pr: none

resources:
  repositories:
    - repository: CMTeam
      type : github
      endpoint: MyGithubServiceConnection
      name: RamkrishnaKakani/CMTeam
      ref : master

stages:
  - stage: Infra_Import
    displayName: Import Others
    jobs:
      - job: Compile_Publish_job
        steps:
        - checkout: self
        - checkout: CMTeam

  - template: ..\infra\Template\terraform_deploy.yml
    parameters:
      environment: "$(env)"
      working_dir: "$(Build.SourcesDirectory)"
      serviceconn_name : "Terraform_ServiceConnection"
      project_name : "$(project)"          