trigger:
  branches:
    include:
      - development
      - master
  paths:
    include:
     - source/*
    exclude:
      - build/*
      - infra/*
      - deploy/*
pr:
  branches:
    include:
      - development
      - master
  paths:
    include:
     - source/*
    exclude:
      - build/*
      - infra/*
      - deploy/*

resources:
  repositories:
    - repository: CMTeam
      type : github
      endpoint: MyGithubServiceConnection
      name: RamkrishnaKakani/CMTeam
      ref : master

  pipelines:
  - pipeline: Project_Sample_Build
    source: Project_Sample_Build
    trigger: 
      branches:
        include: 
        - master
        - development      

steps:
- checkout: self
- checkout: CMTeam

- template: Template/terraform_deploy.yml
  parameters:
    environment: "$(env)"
    working_dir: "$(Build.SourcesDirectory)/CMTeam/infra"
    serviceconn_name : "Terraform_ServiceConnection"
    project_name : "$(project)" 

- download: Project_Sample_Build
  artifact: 'drop'

 