trigger: none
pr: none

resources:
  repositories:
    - repository: CMTeam
      type : github
      endpoint: MyGithubServiceConnection
      name: RamkrishnaKakani/CMTeam
      ref : master

steps:
- checkout: self
- checkout: CMTeam
 