resources:
  repositories:
    - repository: CMTeam
      type : github
      endpoint: MyGithubServiceConnection
      name: RamkrishnaKakani/CMTeam
      ref : master
      
variables:
  env : 'Dev'
  project : 'todobyram'
  TerraformDestroy : False
  TerraformApply : True

steps:    
- checkout: CMTeam
  displayName : 'Download Infra Repo'

- template: infra/Template/terraform_deploy.yml@CMTeam
  parameters:
    environment: "$(env)"
    working_dir: "$(Build.SourcesDirectory)/infra"
    serviceconn_name : "Terraform_ServiceConnection"
    project_name : "$(project)"