trigger: none
pr: none

resources:
  repositories:
    - repository: Common
      type : github
      endpoint: MyGithubServiceConnection
      name: RamkrishnaKakani/CMTeam
      ref : master

steps:
- checkout: self
- checkout: Common

- template: ..\Template\terraform_deploy.yml
  parameters:
      environment: "$(env)"
      working_dir: "$(Build.SourcesDirectory)/Common/infra"
      serviceconn_name : "Terraform_ServiceConnection"
      project_name : "$(project)"          