trigger:
  - none
pr:
  - none

resources:
  repositories:
    - repository: CMTeam
      type : github
      endpoint: MyGithubServiceConnection
      name: RamkrishnaKakani/CMTeam
      ref : master

  pipelines:
  - pipeline: Project_Sample_Build
    source: Project_Sample_Build
    trigger: true    

steps:
#- checkout: self
#- checkout: CMTeam

#- download: Project_Sample_Build
#  artifact: 'drop'
  
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: '726985fd-b209-4af8-b565-720a49aa5497'
    definition: '31'
    buildVersionToDownload: 'latest'
    artifactName: 'drop'
    targetPath: '$(Build.SourcesDirectory)\build\zip\Project_Sample'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.SourcesDirectory)\build\zip\Project_Sample'
    artifact: 'drop'
    publishLocation: 'pipeline'
 