trigger: none
pr: none

resources:
  repositories:
    - repository: CMTeam
      type : github
      endpoint: MyGithubServiceConnection
      name: RamkrishnaKakani/CMTeam
      ref : master

stages:
  - template: ..\infra\Template\terraform_deploy.yml
    parameters:
      environment: "$(env)"
      working_dir: "$(Build.SourcesDirectory)"
      serviceconn_name : "Terraform_ServiceConnection"
      project_name : "$(project)"          