trigger:
  - none
pr:
  - none

resources:
  repositories:
    - repository: CMTeam
      type : github
      endpoint: MyGithubServiceConnection
      name: RamkrishnaKakani/CMTeam
      ref : master

  pipelines:
  - pipeline: Project_Sample_Build
    source: Project_Sample_Build
    trigger: true    

steps:
- checkout: self
- checkout: CMTeam

- template: Template/terraform_deploy.yml
  parameters:
    environment: "$(env)"
    working_dir: "$(Build.SourcesDirectory)/CMTeam/infra"
    serviceconn_name : "Terraform_ServiceConnection"
    project_name : "$(project)" 

- download: Project_Sample_Build
  artifact: 'drop'

 