name: Build and Deploy 

env:
  AZURE_WEBAPP_NAME: demowebappfromram 
  AZURE_WEBAPP_PACKAGE_PATH: '.'      
  DOTNET_VERSION: '5.0.x'                 

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set-up
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
       
      - name: Restore
        run: dotnet restore
        working-directory: source/
      
      - name: Build
        run: dotnet build --configuration Release --no-restore /p:PackageLocation="../My-WebApp" /p:OutDir="../My-WebApp" /p:platform="Any CPU"
        working-directory: source/

      - name: Publish
        run: dotnet publish --configuration Release -r win-x64 --self-contained true /p:DebugType=None /p:DebugSymbols=false /p:PublishArtifact=true --output ../My-WebApp -v d
        working-directory: source/

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: My-WebApp
          path: source/My-WebApp 

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: My-WebApp

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
