name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: source/
      
    - name: Build
      run: |
        #dotnet build --no-restore
        #dotnet build --configuration Release --no-restore
        dotnet build --configuration Release --no-restore /p:PackageLocation="../My-WebApp" /p:OutDir="../My-WebApp" /p:platform="Any CPU"
        dotnet publish --configuration Release -r win-x64 --self-contained true /p:DebugType=None /p:DebugSymbols=false /p:PublishArtifact=true --output ../My-WebApp -v d
      working-directory: source/
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: My-WebApp
        path: source/My-WebApp 
