name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: source/
      
    - name: Build
      run: |
        #dotnet build --no-restore
        #dotnet build --configuration Release --no-restore
        dotnet build --no-restore /p:PackageLocation="../My-WebApp" /p:OutDir="../My-WebApp" /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /maxcpucount:1 /p:platform="Any CPU" /p:configuration="Release"
        dotnet publish --configuration Release -r win-x64 --self-contained true /p:DebugType=None /p:DebugSymbols=false --output ../My-WebApp -v d
      working-directory: source/
