name: .NET

on:
  workflow_dispatch:

jobs:
  build:  
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: source/
      
    - name: Build with dotnet
      run: dotnet build --configuration Release
      working-directory: source/

    - name: dotnet publish
      run: dotnet publish -c Release -o source/myapp
      working-directory: source/

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: My-WebApp
        path: source/myapp
